const teamLogos = {

  // ===== LA LIGA =====
  "Athletic Bilbao": "https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg",
  "Atlético Madrid": "https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg",
  "Barcelona": "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
  "Celta Vigo": "https://upload.wikimedia.org/wikipedia/en/1/10/RC_Celta_de_Vigo_logo.svg",
  "Deportivo Alavés": "https://upload.wikimedia.org/wikipedia/en/5/5e/Deportivo_Alav%C3%A9s_logo.svg",
  "Elche": "https://upload.wikimedia.org/wikipedia/en/0/03/Elche_CF_logo.svg",
  "Espanyol": "https://upload.wikimedia.org/wikipedia/en/8/85/Rcd_espanyol_logo.svg",
  "Getafe": "https://upload.wikimedia.org/wikipedia/en/5/5c/Getafe_CF_logo.svg",
  "Girona": "https://upload.wikimedia.org/wikipedia/en/9/90/Girona_FC_Logo.svg",
  "Levante": "https://upload.wikimedia.org/wikipedia/en/5/56/Levante_UD_logo.svg",
  "Mallorca": "https://upload.wikimedia.org/wikipedia/en/7/7e/Rcd_mallorca_logo.svg",
  "Osasuna": "https://upload.wikimedia.org/wikipedia/en/4/4e/CA_Osasuna_logo.svg",
  "Rayo Vallecano": "https://upload.wikimedia.org/wikipedia/en/1/1e/Rayo_Vallecano_logo.svg",
  "Real Betis": "https://upload.wikimedia.org/wikipedia/en/1/13/Real_betis_logo.svg",
  "Real Madrid": "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
  "Real Oviedo": "https://upload.wikimedia.org/wikipedia/en/3/3f/Real_Oviedo_logo.svg",
  "Real Sociedad": "https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg",
  "Sevilla": "https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg",
  "Valencia": "https://upload.wikimedia.org/wikipedia/en/c/ce/Valenciacf.svg",
  "Villarreal": "https://upload.wikimedia.org/wikipedia/en/7/70/Villarreal_CF_logo.svg",

  // ===== PREMIER LEAGUE =====
  "Arsenal": "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
  "Aston Villa": "https://upload.wikimedia.org/wikipedia/en/f/f9/Aston_Villa_FC_crest_%282016%29.svg",
  "Bournemouth": "https://upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth_%282013%29.svg",
  "Brentford": "https://upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg",
  "Brighton and Hove Albion": "https://upload.wikimedia.org/wikipedia/en/f/fd/Brighton_%26_Hove_Albion_logo.svg",
  "Burnley": "https://upload.wikimedia.org/wikipedia/en/6/62/Burnley_F.C._Logo.svg",
  "Chelsea": "https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg",
  "Crystal Palace": "https://upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo_%282022%29.svg",
  "Everton": "https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg",
  "Fulham": "https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg",
  "Leeds United": "https://upload.wikimedia.org/wikipedia/en/5/54/Leeds_United_F.C._logo.svg",
  "Liverpool": "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
  "Manchester City": "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
  "Manchester United": "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg",
  "Newcastle United": "https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg",
  "Sunderland": "https://upload.wikimedia.org/wikipedia/en/7/77/Logo_Sunderland.svg",
  "Nottingham Forest": "https://upload.wikimedia.org/wikipedia/en/e/e5/Nottingham_Forest_F.C._logo.svg",
  "Tottenham Hotspur": "https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg",
  "West Ham United": "https://upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC_logo.svg",
  "Wolverhampton Wanderers": "https://upload.wikimedia.org/wikipedia/en/f/fc/Wolverhampton_Wanderers.svg",


  // ===== SERIE A =====
  "AC Milan": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg",
  "Atalanta": "https://upload.wikimedia.org/wikipedia/en/6/66/AtalantaBC.svg",
  "Bologna": "https://upload.wikimedia.org/wikipedia/en/5/5b/Bologna_FC_1909_logo.svg",
  "Cagliari": "https://upload.wikimedia.org/wikipedia/en/6/66/Cagliari_Calcio_logo.svg",
  "Como": "https://upload.wikimedia.org/wikipedia/en/5/56/Como_1907_logo.svg",
  "Cremonese": "https://upload.wikimedia.org/wikipedia/en/f/f8/US_Cremonese_logo.svg",
  "Fiorentina": "https://upload.wikimedia.org/wikipedia/en/f/f2/ACF_Fiorentina_logo.svg",
  "Genoa": "https://upload.wikimedia.org/wikipedia/en/2/2d/Genoa_CFC_logo.svg",
  "Hellas Verona": "https://upload.wikimedia.org/wikipedia/en/5/5d/Hellas_Verona_FC_logo.svg",
  "Inter Milan": "https://upload.wikimedia.org/wikipedia/en/0/05/FC_Internazionale_Milano_2021.svg",
  "Juventus": "https://upload.wikimedia.org/wikipedia/commons/1/15/Juventus_FC_2017_logo.svg",
  "Lazio": "https://upload.wikimedia.org/wikipedia/en/c/ce/S.S._Lazio_badge.svg",
  "Lecce": "https://upload.wikimedia.org/wikipedia/en/7/70/US_Lecce_logo.svg",
  "Napoli": "https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Napoli_logo.svg",
  "Parma": "https://upload.wikimedia.org/wikipedia/en/3/3e/Parma_Calcio_1913_logo.svg",
  "Pisa": "https://upload.wikimedia.org/wikipedia/en/5/55/Pisa_SC_logo.svg",
  "Roma": "https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo.svg",
  "Sassuolo": "https://upload.wikimedia.org/wikipedia/en/4/4e/US_Sassuolo_Calcio_logo.svg",
  "Torino": "https://upload.wikimedia.org/wikipedia/en/e/e0/Torino_FC_Logo.svg",
  "Udinese": "https://upload.wikimedia.org/wikipedia/en/6/6c/Udinese_Calcio_logo.svg",

  // ===== BUNDESLIGA =====
  "Bayer Leverkusen": "https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg",
  "Bayern Munich": "https://upload.wikimedia.org/wikipedia/en/1/1f/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg",
  "Borussia Dortmund": "https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg",
  "Borussia Mönchengladbach": "https://upload.wikimedia.org/wikipedia/en/8/81/Borussia_M%C3%B6nchengladbach_logo.svg",
  "Borussia Monchengladbach": "https://upload.wikimedia.org/wikipedia/en/8/81/Borussia_M%C3%B6nchengladbach_logo.svg",
  "Eintracht Frankfurt": "https://upload.wikimedia.org/wikipedia/en/0/04/Eintracht_Frankfurt_Logo.svg",
  "FC Augsburg": "https://upload.wikimedia.org/wikipedia/en/8/8c/FC_Augsburg_logo.svg",
  "FC Heidenheim": "https://upload.wikimedia.org/wikipedia/en/2/2d/1._FC_Heidenheim_logo.svg",
  "FC Köln": "https://upload.wikimedia.org/wikipedia/en/5/5a/1._FC_K%C3%B6ln_logo.svg",
  "Freiburg": "https://upload.wikimedia.org/wikipedia/en/f/f1/SC_Freiburg_logo.svg",
  "Hamburg": "https://upload.wikimedia.org/wikipedia/commons/6/6d/HSV_Logo.svg",
  "Hoffenheim": "https://upload.wikimedia.org/wikipedia/en/7/72/TSG_1899_Hoffenheim_logo.svg",
  "Mainz": "https://upload.wikimedia.org/wikipedia/en/0/0f/FSV_Mainz_05_logo.svg",
  "RB Leipzig": "https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg",
  "St Pauli": "https://upload.wikimedia.org/wikipedia/commons/7/74/FC_St._Pauli_logo.svg",
  "Stuttgart": "https://upload.wikimedia.org/wikipedia/en/e/eb/VfB_Stuttgart_1893_Logo.svg",
  "Union Berlin": "https://upload.wikimedia.org/wikipedia/en/e/e4/1._FC_Union_Berlin_logo.svg",
  "Werder Bremen": "https://upload.wikimedia.org/wikipedia/en/b/be/SV-Werder-Bremen-Logo.svg",
  "Wolfsburg": "https://upload.wikimedia.org/wikipedia/en/0/08/VfL_Wolfsburg_logo.svg"
};

export default teamLogos;
